// ChartFunctions index: exports all bespoke chart generators
module.exports = {
    uwStoneCostChart: require('./uwStoneCostChart.js'),
    enemyBalanceMasteryChart: require('./enemyBalanceMasteryChart.js'),
    waveAcceleratorSpawnRatesChart: require('./waveAcceleratorSpawnRatesChart.js'),
    recoveryPackageDropRatesChart: require('./recoveryPackageDropRatesChart.js'),
    waveSkipCoinBoostChart: require('./waveSkipCoinBoostChart.js'),
    eliteSpawnChanceChart: require('./eliteSpawnChanceChart.js'),
    cardMasteryCostChart: require('./cardMasteryCostChart.js'),
    labSpeedMultiplierChart: require('./labSpeedMultiplierChart.js'),
    uwPlusUpgradesChart: require('./uwPlusUpgradesChart.js'),
    moduleSubstatValuesChart: require('./moduleSubstatValuesChart.js'),
    botUpgradesChart: require('./botUpgradesChart.js'),
    guildBoxRewardsChart: require('./guildBoxRewardsChart.js'),
    avgBulletsToStackShockChart: require('./avgBulletsToStackShockChart.js'),
    chainThunderDmgReductionChart: require('./chainThunderDmgReductionChart.js'),
    bonusMultipliersChart: require('./bonusMultipliersChart.js'),
    goldBotVsDeathWaveUptimeChart: require('./goldBotVsDeathWaveUptimeChart.js'),
    EOvsSLABreakpointsChart: require('./EOvsSLABreakpointsChart.js'),
    CFPlusRotationRatesChart: require('./CFPlusRotationRatesChart.js'),
    CFPlusSpeedRatesChart: require('./CFPlusSpeedRatesChart.js'),
    waveSkipMultiSkipChanceChart: require('./waveSkipMultiSkipChanceChart.js'),
    permaSwampStoneCostChart: require('./permaSwampStoneCostChart.js'),
    harmonyTreeUpgradesChart: require('./harmonyTreeUpgradesChart.js'),
    powerTreeUpgradesChart: require('./powerTreeUpgradesChart.js'),
};
