import { TOOL_LAB_SPEEDUP_OPTIONS } from '@tmrxjd/platform/tools'

export const defaultBotConfig = {
  meta: {
    botName: 'Tower Tools Bot',
  },
  common: {
    responses: {
      commandNotFound: 'Command not found.',
      interactionError: 'There was an error handling this interaction.',
    },
    toolsHub: {
      title: "JD's Tools Hub",
      footer: 'To use this command type /tools',
      siteUrl: 'https://www.the-tower-run-tracker.com',
      toolsPath: '/tools',
      embedColor: '#00bfff',
    },
  },
  commands: {
    ping: {
      name: 'ping',
      description: 'Replies with Pong!',
      reply: 'Pong!',
    },
    server: {
      name: 'server',
      description: 'Provides information about the server.',
      unknownServer: 'Unknown server',
      responseTemplate: 'This server is {guildName} and has {memberCount} members.',
    },
    user: {
      name: 'user',
      description: 'Provides information about the user.',
      unknownDate: 'unknown date',
      responseTemplate: 'This command was run by {username}, who joined on {joinedText}.',
    },
    creator: {
      name: 'creator',
      description: 'List known creators and their codes',
      title: 'Known Creators & Codes',
      footer: 'If a creator is missing or needs updating, contact a moderator.',
      color: '#00bfff',
      knownForPrefix: 'Known for:',
      creators: [
        { id: '393181619911131146', code: '1410c', known: 'Moderating | Sheets & Tools' },
        { id: '398318678673719296', code: 'cruoton', known: 'Moderating | Extensive Game Knowledge | Mentoring' },
        { id: '349704551391297549', code: 'icetae', known: 'Moderating | TDC co-founder' },
        { id: '371914184822095873', code: 'jdevo', known: 'Moderating | https://the-tower-run-tracker.com/ | Discord Bots | Server Events' },
        { id: '204350672714465280', code: 'sheetlord', known: 'Moderating | https://discord.com/channels/850137217828388904/1379468947685904404/1379470428912746506' },
        { id: '92034793302138880', code: 'VCMomo', known: 'Moderating' },
        { id: '480857237380923393', code: 'nickavii', known: 'Moderating' },
        { id: '96626874708430848', code: 'PogTheMightyOne', known: 'Moderating | Discord Bots' },
        { id: '197431930877116416', code: 'duckirons', known: 'Moderating' },
        { id: '169201175231463424', code: 'TheDisasterFish', known: 'Moderating | thetower.lol | Discord Bots' },
        { id: '138163202516058112', code: 'crowrocks', known: 'https://www.youtube.com/@crowbarzero' },
        { id: '121649684384055299', code: 'Darknyxzz', known: 'Moderating | Sheets' },
        { id: '200927253809332224', code: 'Iver', known: 'Moderating' },
        { id: '530860087384735775', code: 'jplays', known: 'https://www.youtube.com/@JPlays1 | https://the-tower.notion.site/' },
        { id: '280723745864286208', code: 'Milamber33', known: 'Moderating' },
        { id: '150761026718007296', code: 'NanaSeiYuri', known: 'Moderating | Making Sheets & Infografics' },
        { id: '211865455697068032', code: 'ronmv', known: 'Moderating' },
        { id: '164886229328855040', code: 'Shion', known: 'Moderating' },
        { id: '767167088485335041', code: '300', known: 'https://www.youtube.com/@SpartanTheTower' },
        { id: '928167650352300092', code: 'Zaerdin', known: 'https://www.youtube.com/@ZaerdinGaming' },
      ],
    },
    define: {
      name: 'define',
      description: 'Auto-expand known acronyms',
      options: {
        text: { name: 'text', description: 'Text to convert acronyms in' },
        public: { name: 'public', description: 'If true, response is visible to everyone (default: private)' },
      },
      noAcronyms: 'No known acronyms detected.',
    },
    defineMessage: {
      name: 'Define Acronyms',
      noAcronyms: 'No known acronyms detected.',
    },
    meow: {
      name: 'meow',
      description: 'Send a random cat emoji',
      behavior: {
        perUserBurstWindowMs: 60_000,
        perUserSingleCooldownMs: 10_000,
        perUserBurstLimit: 3,
      },
      emoji: {
        catPrefix: 'cat_',
        stretchyToken: 'STRETCHY_SET',
        stretchySets: [
          ['cat_stretchy_top', 'cat_stretchy_mid', 'cat_stretchy_bottom'],
        ],
      },
      rateLimitSingle: 'Slow down, one meow every 10s. Try again in {seconds}s.',
      rateLimitBurst: 'Too many meows. Limit is 3 per minute. Try again in {seconds}s.',
      emojiFetchError: 'I could not fetch cat emojis right now. Try again in a moment.',
      noCats: 'No cat emojis found. Add some cat_ emojis to the application emoji list.',
    },
    tools: {
      name: 'tools',
      description: 'Open the tools hub',
    },
    chart: {
      name: 'chart',
      description: 'Browse The Tower chart catalog',
      behavior: {
        collectorTimeoutMs: 10 * 60 * 1000,
        modalSubmitTimeoutMs: 120000,
        imageUploadTimeoutMs: 120000,
      },
      ids: {
        categorySelect: 'chart_category',
        subcategorySelect: 'chart_subcategory',
        itemSelect: 'chart_item',
        statFilterSelect: 'chart_stat_filter',
        noneValue: 'none',
      },
      ui: {
        title: 'The Tower Chart Finder',
        description: 'Select a category, subcategory, and chart to view.',
        categoryPlaceholder: 'Select a category',
        subcategoryPlaceholder: 'Select a subcategory',
        itemPlaceholder: 'Select a chart',
        categoryDescriptionTemplate: 'View charts for {category}',
        subcategoryDescriptionTemplate: 'View {subcategory} charts',
        itemDescriptionTemplate: 'View {item} chart details',
        statFilterPlaceholder: 'Filter stats',
        statFilterDescriptionTemplate: 'Show or hide the {stat} stat',
        noneLabel: 'No options',
        noneSubcategories: 'No subcategories available',
        noneItems: 'No chart items available',
        statusField: 'Selection',
        selectedTemplate: 'Selected: **{category} → {subcategory} → {item}**\nChart ID: `{id}`\nRenderer: {rendererStatus}',
        rendererReady: 'ready (image output available)',
        rendererPending: 'pending migration',
        rendererErrorField: 'Renderer Error',
        rendererErrorTemplate: 'Could not render this chart image right now. You can still use this selection path and ID. Error: {message}',
        creatorField: 'Creator',
        notReady: 'Select a complete category path to view chart metadata.',
        siteHintTemplate: 'Upcoming site route: {url}',
        closedTitle: 'Chart Finder Closed',
        closedDescription: 'Chart finder closed.',
        timeoutDescription: 'Chart finder closed due to inactivity. Use /chart to start again.',
      },
      color: 0x3b82f6,
    },
    cph: {
      name: 'cph',
      description: 'Calculate resources earned per hour',
      options: {
        time: { name: 'time', description: 'Enter game time (e.g., 5h10m14s)' },
        coins: { name: 'coins', description: 'Enter coins earned (e.g., 1k, 1M, 1B)' },
        cells: { name: 'cells', description: 'Enter cells earned (e.g., 1k, 1M, 1B)' },
        dice: { name: 'dice', description: 'Enter dice earned (e.g., 1k, 1M, 1B)' },
      },
      invalidTime: 'Invalid time input! Make sure to enter at least some time.',
      missingResources: 'Provide at least one resource amount (coins, cells, dice).',
      invalidAmountsPrefix: 'Invalid amount provided for: ',
      invalidAmountsHint: '. Use values like 1k, 2.5M, 10B.',
      responseHeaderPrefix: 'Game time: ',
      coinsLineTemplate: 'Coins: {total} total → {rate}/hr',
      cellsLineTemplate: 'Cells: {total} total → {rate}/hr',
      diceLineTemplate: 'Dice: {total} total → {rate}/hr',
    },
    module: {
      name: 'module',
      description: 'Calculate primary and assist module costs with rarity and type parity',
      defaults: {
        coinDiscount: 0,
        shardDiscount: 0,
      },
      behavior: {
        previewRows: 10,
        collectorTimeoutMs: 10 * 60 * 1000,
        modalSubmitTimeoutMs: 120000,
      },
      ids: {
        moduleTypeSelect: 'module_type_select',
        primaryValues: 'module_primary_values',
        assistValues: 'module_assist_values',
        toggleView: 'module_toggle_view',
        primaryModal: 'module_primary_modal',
        assistModal: 'module_assist_modal',
        primaryRaritySelect: 'module_primary_rarity',
        assistRaritySelect: 'module_assist_rarity',
        currentLevelInput: 'module_current_level',
        targetLevelInput: 'module_target_level',
        assistCurrentLevelInput: 'module_assist_current_level',
        assistTargetLevelInput: 'module_assist_target_level',
        coinDiscountInput: 'module_coin_discount',
        shardDiscountInput: 'module_shard_discount',
        assistEffInput: 'module_assist_eff',
      },
      options: {
        currentLevel: { name: 'current_level', description: 'Current level (1+)' },
        targetLevel: { name: 'target_level', description: 'Target level (1-300, capped by rarity in the UI)' },
        coinDiscount: { name: 'coin_discount', description: 'Coin discount percent (0-100)' },
        shardDiscount: { name: 'shard_discount', description: 'Shard discount percent (0-100)' },
      },
      ui: {
        title: 'Module Cost Calculator',
        summaryTemplate: 'Type: {moduleType}\nViewing: {viewLabel}\nPrimary: {rarity} {from} → {to}\nAssist: {assistRarity} {assistFrom} → {assistTo} @ {assistEff}%\nDiscounts: Coin {coinDiscount}% | Shard {shardDiscount}%',
        totalsFieldName: 'Totals',
        totalsTemplate: 'Primary: {primaryCoinTotal} coin | {primaryShardTotal} shard\nAssist: {assistCoinTotal} coin | {assistShardTotal} shard | {assistStoneTotal} stones\nPreview Rows: {rows}',
        description: 'Use the module type dropdown, then open Primary or Assist to adjust values.',
        moduleTypePlaceholder: 'Select module type',
        primaryValuesLabel: 'Edit Primary',
        assistValuesLabel: 'Edit Assist',
        viewPrimaryLabel: 'Show Primary',
        viewAssistLabel: 'Show Assist',
        primaryModalTitle: 'Primary',
        assistModalTitle: 'Assist',
        currentLevelLabel: 'Primary Current Level (1-300)',
        targetLevelLabel: 'Primary Target Level (1-300)',
        assistCurrentLevelLabel: 'Assist Current Level (1-300)',
        assistTargetLevelLabel: 'Assist Target Level (1-300)',
        coinDiscountLabel: 'Coin Discount % (0-100)',
        shardDiscountLabel: 'Shard Discount % (0-100)',
        assistEffLabel: 'Assist Efficiency % (0-100)',
        primaryRarityLabel: 'Primary Rarity',
        assistRarityLabel: 'Assist Rarity',
        primaryRarityPlaceholder: 'Select primary rarity',
        assistRarityPlaceholder: 'Select assist rarity',
        invalidPrimaryInput: 'Invalid primary values. Check rarity, level, or discount ranges.',
        invalidAssistInput: 'Invalid assist values. Check rarity, level, or efficiency ranges.',
        notYourSession: 'This module calculator session belongs to someone else.',
        sessionTimedOut: 'Module calculator timed out. Run /module again.',
      },
      color: 0xf59e0b,
    },
    lab: {
      name: 'lab',
      description: 'The Tower Lab Calculator',
      defaults: {
        labSpeed: 0,
        labRelic: 0,
        labDiscount: 0,
        speedUp: 1,
      },
      behavior: {
        previewRows: 10,
        collectorTimeoutMs: 15 * 60 * 1000,
        modalSubmitTimeoutMs: 120000,
      },
      speedUpChoices: [...TOOL_LAB_SPEEDUP_OPTIONS],
      ids: {
        category: 'lab_category',
        lab: 'lab_lab',
        speedup: 'lab_speedup',
        uwType: 'uw_type',
        settings: 'lab_settings',
        range: 'lab_range',
        toggleHideMaxed: 'lab_toggle_hide_maxed',
        close: 'lab_close',
        settingsModal: 'lab_settings_modal',
        rangeModal: 'lab_range_modal',
        settingsLabSpeed: 'labSpeed',
        settingsLabRelic: 'labRelic',
        settingsLabDiscount: 'labDiscount',
        rangeStartLevel: 'startLevel',
        rangeTargetLevel: 'targetLevel',
      },
      ui: {
        title: 'Lab Calculator',
        settingsIntro: 'Your current settings:',
        labSpeedField: 'Lab\nSpeed',
        labRelicField: 'Lab\nRelic',
        coinDiscountField: 'Coin\nDiscount',
        currentLevelField: 'Current\nLab Level',
        targetLevelField: 'Target\nLab Level',
        maxLevelField: 'Max\nLab Level',
        previewFieldName: 'Level Preview',
        totalsFieldName: 'Totals',
        tableHeader: 'Lvl | Value | Time | Gems | Coins',
        totalsTemplate: 'Time: {time}\nGems: {gems}\nCoins: {coins}\nSpeed Up: {speedUp}',
        chartFooterSettingsTemplate: 'Lab Speed {labSpeed} • Relic {labRelic}% • Coin Disc {coinDiscount}% • Speed Up {speedUp}x',
        categoryPlaceholder: 'Select a category',
        labPlaceholder: 'Select a lab',
        speedupPlaceholder: 'Select Speedup',
        uwTypePlaceholder: 'Select Ultimate Weapon',
        noCategories: 'No categories found',
        noLabs: 'No labs found',
        allUwMaxed: 'All UW types maxed',
        settingsButton: 'Settings',
        rangeButton: 'Range',
        hideMaxedButton: 'Hide Completed',
        showMaxedButton: 'Show Completed',
        closeButton: 'Close',
        settingsModalTitle: 'Lab Base Settings',
        settingsLabSpeedLabel: 'Lab Speed Level',
        settingsLabRelicLabel: 'Lab Relic %',
        settingsLabDiscountLabel: 'Lab Coin Disc %',
        rangeModalTitle: 'Lab Range Settings',
        rangeStartLabel: 'Current Lab Level (0 - {max})',
        rangeTargetLabel: 'Target Lab Level (0 - {max})',
        notYourSession: 'This is not your calculator session.',
        closed: 'Closed.',
        sessionEnded: 'Lab calculator session ended.',
        noRows: 'No valid levels were found in that range for the selected lab.',
      },
      color: 0x10b981,
    },
    workshop: {
      name: 'workshop',
      description: 'Calculate workshop upgrade costs for a stat and level range',
      defaults: {
        mode: 'normal',
        section: 'attack',
        stat: 'damage',
        currentLevel: 0,
        targetLevel: 10,
        discount: 0,
        vaultDiscount: 0,
        hideBaseCosts: true,
      },
      behavior: {
        previewRows: 10,
        collectorTimeoutMs: 10 * 60 * 1000,
        modalSubmitTimeoutMs: 120000,
      },
      ids: {
        modeSelect: 'workshop_mode_select',
        sectionSelect: 'workshop_section_select',
        statSelect: 'workshop_stat_select',
        setValues: 'workshop_set_values',
        toggleBaseCosts: 'workshop_toggle_base_costs',
        valuesModal: 'workshop_values_modal',
        currentLevelInput: 'workshop_current_level',
        targetLevelInput: 'workshop_target_level',
        discountInput: 'workshop_discount',
        vaultDiscountInput: 'workshop_vault_discount',
      },
      options: {
        mode: { name: 'mode', description: 'Workshop (normal or enhancements)' },
        section: { name: 'section', description: 'Workshop section' },
        stat: { name: 'stat', description: 'Workshop stat' },
        currentLevel: { name: 'current_level', description: 'Current level (0+)' },
        targetLevel: { name: 'target_level', description: 'Target level' },
        discount: { name: 'discount', description: 'Workshop discount percent (0-100)' },
        vaultDiscount: { name: 'vault_discount', description: 'Vault discount percent (0-100)' },
      },
      modeChoices: [
        { name: 'Workshop', value: 'normal' },
        { name: 'Enhancements', value: 'enhancements' },
      ],
      sectionChoices: [
        { name: 'Attack', value: 'attack' },
        { name: 'Defense', value: 'defense' },
        { name: 'Utility', value: 'utility' },
      ],
      statChoices: [
        { name: 'Damage', value: 'damage' },
        { name: 'Rend Armor', value: 'rend_armor' },
        { name: 'Critical Factor', value: 'critical_factor' },
        { name: 'Damage / Meter', value: 'damage_meter' },
        { name: 'Super Crit Mult', value: 'super_crit_mult' },
        { name: 'Attack Speed', value: 'attack_speed' },
        { name: 'Health', value: 'health' },
        { name: 'Health Regen', value: 'health_regen' },
        { name: 'Defense Absolute', value: 'defense_absolute' },
        { name: 'Land Mine Damage', value: 'land_mine_damage' },
        { name: 'Wall Health', value: 'wall_health' },
        { name: 'Orb Size', value: 'orb_size' },
        { name: 'Cash Bonus', value: 'cash_bonus' },
        { name: 'Coin Bonus', value: 'coin_bonus' },
        { name: 'Cells / Kill Bonus', value: 'cells_per_kill_bonus' },
        { name: 'Free Upgrades', value: 'free_upgrades' },
        { name: 'Recovery Package', value: 'recovery_package' },
        { name: 'Enemy Level Skip', value: 'enemy_level_skip' },
      ],
      ui: {
        title: 'Workshop Calculator',
        normalSummaryTemplate: 'Workshop • {section} • {stat} • Levels {from} → {to} • Coin Disc {discount}%',
        normalTableFieldName: 'Cost Preview',
        normalTableHeader: 'Lvl | Value | Coin Cost | Cash Cost | Coin Total | Cash Total',
        normalTotalsTemplate: 'Coin Total: {coinTotal}\nCash Total: {cashTotal}\nRows: {rows}',
        summaryTemplate: '{section} • {stat} • Levels {from} → {to} • Disc {discount}%',
        enhancementDiscountDetailsTemplate: 'Section Disc: {sectionDiscount}% • Vault Disc: {vaultDiscount}% • Total Disc: {totalDiscount}%',
        tableFieldName: 'Level Cost Preview',
        totalsFieldName: 'Totals',
        tableHeader: 'Lvl | Base Cost | Disc Cost | Total',
        totalsTemplate: 'Total Cost: {total}\nRows: {rows}',
        invalidStat: 'Selected stat is not available in workshop data.',
        description: 'Pick type, section, and stat, then set level range and discount.',
        modePlaceholder: 'Select workshop type',
        sectionPlaceholder: 'Select workshop section',
        statPlaceholder: 'Select workshop stat',
        setValuesLabel: 'Set Values',
        hideBaseCostsLabel: 'Hide Base Costs',
        showBaseCostsLabel: 'Show Base Costs',
        valuesModalTitle: 'Workshop Range and Discount',
        currentLevelLabel: 'Current Level (0+)',
        targetLevelLabel: 'Target Level (> current)',
        discountLabel: 'Disc % (0-100)',
        vaultDiscountLabel: 'Vault Disc %',
        invalidInput: 'Invalid values. Check level range and discount.',
        notYourSession: 'This workshop calculator session belongs to someone else.',
        sessionTimedOut: 'Workshop calculator timed out. Run /workshop again.',
      },
      color: 0x6366f1,
    },
    stone: {
      name: 'stone',
      description: 'Calculate Ultimate Weapon stone costs',
      defaults: {
        stat: 'all',
        startLevel: 0,
      },
      behavior: {
        previewRows: 12,
        collectorTimeoutMs: 10 * 60 * 1000,
        modalSubmitTimeoutMs: 120000,
      },
      ids: {
        weaponSelect: 'stone_weapon_select',
        statSelect: 'stone_stat_select',
        setRange: 'stone_set_range',
        rangeModal: 'stone_range_modal',
        startLevelInput: 'stone_start_level',
        targetLevelInput: 'stone_target_level',
      },
      options: {
        weapon: { name: 'weapon', description: 'Ultimate Weapon name (e.g., Golden Tower, Spotlight)' },
        stat: { name: 'stat', description: 'Stat name (or all)' },
        startLevel: { name: 'start_level', description: 'Current stat level (0+)' },
        targetLevel: { name: 'target_level', description: 'Target stat level (defaults to max)' },
      },
      ui: {
        title: 'UW Stone Cost Calculator',
        description: 'Pick a weapon and stat, then set your level range.',
        tableFieldName: 'Level Cost Preview',
        totalsFieldName: 'Totals',
        tableHeader: 'Lvl | Value | Cost | Total',
        summaryTemplate: '{weapon} • {stat} • Levels {start} → {target}',
        totalsTemplate: 'Stones Required: {stones}\nRows: {rows}',
        allStatsSummaryTemplate: '{weapon} • All Stats • Levels {start} → {target}',
        selectedStatsSummaryTemplate: '{weapon} • Selected Stats ({count}) • Levels {start} → {target}',
        allStatsDetailsTemplate: 'Stones Required: {stones}',
        unknownWeaponTemplate: 'Unknown Ultimate Weapon: {weapon}',
        unknownStatTemplate: 'Unknown stat "{stat}" for {weapon}',
        weaponPlaceholder: 'Select ultimate weapon',
        weaponDescriptionTemplate: 'Use {weapon}',
        statPlaceholder: 'Select stat (or all)',
        statAllLabel: 'All Stats',
        statAllDescription: 'Calculate total stones across all stats',
        statDescriptionTemplate: 'Use {stat}',
        setRangeLabel: 'Set Levels',
        rangeModalTitle: 'Stone Level Range',
        startLevelLabel: 'Start Level (0+)',
        targetLevelLabel: 'Target Level',
        invalidInput: 'Invalid level values.',
        notYourSession: 'This stone calculator session belongs to someone else.',
        sessionTimedOut: 'Stone calculator timed out. Run /stone again.',
      },
      color: 0xef4444,
    },
    bots: {
      name: 'bots',
      description: 'Calculate Bot medal costs for a level range',
      defaults: {
        stat: 'all',
        startLevel: 0,
        cooldownLab: 0,
        durationLab: 0,
      },
      behavior: {
        previewRows: 12,
        collectorTimeoutMs: 10 * 60 * 1000,
        modalSubmitTimeoutMs: 120000,
      },
      ids: {
        botSelect: 'bots_bot_select',
        statSelect: 'bots_stat_select',
        levelButton: 'bots_set_levels',
        levelsModal: 'bots_levels_modal',
        startLevelInput: 'bots_start_level',
        targetLevelInput: 'bots_target_level',
        cooldownLabInput: 'bots_cooldown_lab',
        durationLabInput: 'bots_duration_lab',
      },
      options: {
        bot: { name: 'bot', description: 'Bot name (Flame Bot, Thunder Bot, Coin Bot, Amplify Bot)' },
        stat: { name: 'stat', description: 'Stat name (or all)' },
        startLevel: { name: 'start_level', description: 'Current stat level (0+)' },
        targetLevel: { name: 'target_level', description: 'Target stat level (defaults to max)' },
        cooldownLab: { name: 'cooldown_lab', description: 'Cooldown lab level (0-25)' },
        durationLab: { name: 'duration_lab', description: 'Duration lab level (0-20)' },
      },
      botChoices: [
        { name: 'Flame Bot', value: 'Flame Bot' },
        { name: 'Thunder Bot', value: 'Thunder Bot' },
        { name: 'Coin Bot', value: 'Coin Bot' },
        { name: 'Amplify Bot', value: 'Amplify Bot' },
      ],
      ui: {
        title: 'Bot Medal Cost Calculator',
        description: 'Select a bot, choose a stat filter, then use Set Levels to calculate medals.',
        tableFieldName: 'Level Cost Preview',
        totalsFieldName: 'Totals',
        breakdownFieldName: 'Stat Breakdown',
        tableHeader: 'Lvl | Value | Cost | Total',
        summaryTemplate: '{bot} • {stat} • Levels {start} → {target}',
        totalsTemplate: 'Medals Required: {medals}\nRows: {rows}',
        allStatsSummaryTemplate: '{bot} • All Stats • Requested levels {start} → {target}',
        allStatsLineTemplate: '{stat}: {cost} medals ({start} → {target})',
        allStatsTotalsTemplate: 'Total Medals Required: {total}',
        unknownBotTemplate: 'Unknown bot: {bot}',
        unknownStatTemplate: 'Unknown stat "{stat}" for {bot}',
        maxLabel: 'max',
        botPlaceholder: 'Select a bot',
        botDescriptionTemplate: 'Use {bot} for medal calculations',
        statPlaceholder: 'Filter by stat',
        statAllLabel: 'All Stats',
        statAllDescription: 'Show medal totals across all stats',
        statDescriptionTemplate: 'Show {stat} only',
        levelButtonLabel: 'Set Levels',
        levelsModalTitle: 'Bot Level Range',
        startLevelLabel: 'Start Level',
        targetLevelLabel: 'Target Level',
        cooldownLabLabel: 'Cooldown Lab (0-25)',
        durationLabLabel: 'Duration Lab (0-20)',
        invalidLevelInput: 'Invalid levels. Use numeric values within allowed ranges.',
        notYourSession: 'This bots calculator session belongs to someone else.',
        sessionTimedOut: 'Bots calculator timed out. Use /bots to start again.',
      },
      color: 0xf59e0b,
    },
    thorns: {
      name: 'thorns',
      description: 'Calculate thorns hits-to-kill preview tables',
      defaults: {
        baseThorns: 100,
        tier: 14,
        pcLevel: 0,
        pcMasteryLevel: 0,
        bcLabLevel: 0,
        bcReductionLabLevel: 0,
        pcReductionLabLevel: 0,
        tournamentTier: 'none',
        heatWave: 0,
        sharpFortitude: false,
      },
      behavior: {
        previewRows: 10,
        collectorTimeoutMs: 10 * 60 * 1000,
        modalSubmitTimeoutMs: 120000,
      },
      ids: {
        setCore: 'thorns_set_core',
        setAdvanced: 'thorns_set_advanced',
        coreModal: 'thorns_core_modal',
        advancedModal: 'thorns_advanced_modal',
        baseThornsInput: 'thorns_base',
        tierInput: 'thorns_tier',
        pcLevelInput: 'thorns_pc_level',
        pcMasteryLevelInput: 'thorns_pc_mastery',
        bcLabLevelInput: 'thorns_bc_lab',
        bcReductionInput: 'thorns_bc_reduction',
        pcReductionInput: 'thorns_pc_reduction',
        tournamentInput: 'thorns_tournament',
        heatWaveInput: 'thorns_heat_wave',
        sharpFortitudeInput: 'thorns_sharp_fortitude',
      },
      options: {
        baseThorns: { name: 'base_thorns', description: 'Base thorns percent (0-600)' },
        tier: { name: 'tier', description: 'Tier number (1-21)' },
        pcLevel: { name: 'pc_level', description: 'Plasma Cannon level (0-7)' },
        pcMasteryLevel: { name: 'pc_mastery_level', description: 'Plasma Cannon Mastery level (0-9)' },
        bcLabLevel: { name: 'bc_lab_level', description: 'Battle Condition lab level (0-10)' },
        bcReductionLabLevel: { name: 'bc_reduction_level', description: 'Battle Condition reduction level (0-20)' },
        pcReductionLabLevel: { name: 'pc_reduction_level', description: 'Plasma Cannon reduction level (0-20)' },
        tournamentTier: { name: 'tournament_tier', description: 'Tournament tier override for heat wave values' },
        heatWave: { name: 'heat_wave', description: 'Heat wave for tournament override (0-1000)' },
        sharpFortitude: { name: 'sharp_fortitude', description: 'Apply Sharp Fortitude per-hit scaling' },
      },
      tournamentChoices: [
        { name: 'None', value: 'none' },
        { name: 'T11', value: 't11' },
        { name: 'T14', value: 't14' },
        { name: 'T17', value: 't17' },
      ],
      heatWaveChoices: [0, 20, 40, 60, 80, 100, 150, 200, 250, 300, 350, 400, 450, 500, 600, 700, 800, 900, 1000],
      ui: {
        title: 'Thorns Calculator',
        descriptionTemplate: 'Base {baseThorns}% • Tier {tier} • PC {pcLevel}/{pcMasteryLevel} • BC {bcLabLevel}',
        wallFieldName: 'Wall Thorns (preview)',
        baseFieldName: 'Base Thorns Scaling (preview)',
        settingsFieldName: 'Settings',
        wallTableHeader: 'WT | Elite | Fleet | E+PC | Boss | B+PC',
        baseTableHeader: 'BT | Elite | Fleet | E+PC | Boss | B+PC',
        settingsTemplate: 'BC Red: {bcReduction} • PC Red: {pcReduction} • Tournament: {tournament} • Heat Wave: {heatWave} • Sharp Fortitude: {sharpFortitude}',
        siteHintTemplate: 'Full chart: {url}',
        setCoreLabel: 'Set Core Values',
        setAdvancedLabel: 'Set Advanced',
        coreModalTitle: 'Core Thorns Values',
        advancedModalTitle: 'Advanced Thorns Values',
        baseThornsLabel: 'Base Thorns % (0-600)',
        tierLabel: 'Tier (1-21)',
        pcLevelLabel: 'PC Level (0-7)',
        pcMasteryLabel: 'PC Mastery (0-9)',
        bcLabLabel: 'BC Lab (0-10)',
        bcReductionLabel: 'BC Reduction (0-20)',
        pcReductionLabel: 'PC Reduction (0-20)',
        tournamentLabel: 'Tournament (none/t11/t14/t17)',
        heatWaveLabel: 'Heat Wave (0-1000)',
        sharpFortitudeLabel: 'Sharp Fortitude (true/false)',
        invalidInput: 'Invalid thorns values. Check numeric ranges and tournament value.',
        notYourSession: 'This thorns calculator session belongs to someone else.',
        sessionTimedOut: 'Thorns calculator timed out. Run /thorns again.',
      },
      color: 0x14b8a6,
    },
    enemyStats: {
      name: 'enemy_stats',
      description: 'Enemy HP/damage lookup and ELS vs ELS+ planner',
      behavior: {
        collectorTimeoutMs: 10 * 60 * 1000,
        modalSubmitTimeoutMs: 120000,
        maxSteps: 20,
      },
      ids: {
        modeSelect: 'enemy_stats_mode',
        perkSelect: 'enemy_stats_perks',
        battleConditionSelect: 'enemy_stats_battle_conditions',
        setInputs: 'enemy_stats_set_inputs',
        setElsCore: 'enemy_stats_set_els_core',
        setElsBudget: 'enemy_stats_set_els_budget',
        inputsModal: 'enemy_stats_inputs_modal',
        elsCoreModal: 'enemy_stats_els_core_modal',
        elsBudgetModal: 'enemy_stats_els_budget_modal',
        waveInput: 'enemy_stats_wave',
        tierInput: 'enemy_stats_tier',
        healthSkipInput: 'enemy_stats_health_skip',
        attackSkipInput: 'enemy_stats_attack_skip',
        targetHpInput: 'enemy_stats_target_hp',
        targetDamageInput: 'enemy_stats_target_damage',
        attackLevelInput: 'enemy_stats_attack_level',
        healthLevelInput: 'enemy_stats_health_level',
        enhancementLevelInput: 'enemy_stats_enhancement_level',
        referenceWaveInput: 'enemy_stats_reference_wave',
        focusSelect: 'enemy_stats_focus_select',
        utilityDiscountInput: 'enemy_stats_utility_discount',
        enhancementDiscountInput: 'enemy_stats_enhancement_discount',
        vaultDiscountInput: 'enemy_stats_vault_discount',
        coinBudgetInput: 'enemy_stats_coin_budget',
      },
      modeChoices: [
        { name: 'Wave Lookup', value: 'wave' },
        { name: 'HP Reverse Lookup', value: 'hp' },
        { name: 'Damage Reverse Lookup', value: 'damage' },
        { name: 'ELS vs ELS+', value: 'els' },
      ],
      focusChoices: [
        { name: 'Combined', value: 'combined' },
        { name: 'Attack', value: 'attack' },
        { name: 'Health', value: 'health' },
      ],
      ui: {
        title: 'Enemy Stats',
        description: 'Enemy HP/damage tables and ELS upgrade planning with perks and battle conditions.',
        modePlaceholder: 'Select calculator mode',
        perkPlaceholder: 'Select active perks',
        battleConditionPlaceholder: 'Select battle conditions',
        setInputsLabel: 'Set Inputs',
        setElsCoreLabel: 'Set Levels & Focus',
        setElsBudgetLabel: 'Set Discounts & Budget',
        inputsModalTitle: 'Enemy Stats Inputs',
        elsCoreModalTitle: 'ELS Levels & Focus',
        elsBudgetModalTitle: 'ELS Discounts & Budget',
        waveLabel: 'Wave',
        tierLabel: 'Tier (1-21)',
        healthSkipLabel: 'Health Skip %',
        attackSkipLabel: 'Attack Skip %',
        targetHpLabel: 'Target HP',
        targetDamageLabel: 'Target Damage',
        attackLevelLabel: 'Attack ELS Level',
        healthLevelLabel: 'Health ELS Level',
        enhancementLevelLabel: 'ELS+ Level',
        referenceWaveLabel: 'Reference Wave',
        focusLabel: 'ROI Focus',
        focusPlaceholder: 'Select ROI focus',
        utilityDiscountLabel: 'Utility Coin Discount %',
        enhancementDiscountLabel: 'ELS+ Section Discount %',
        vaultDiscountLabel: 'ELS+ Vault Discount %',
        coinBudgetLabel: 'Coin Budget (blank = no cap)',
        invalidInput: 'Invalid enemy stats inputs for the selected mode.',
        invalidElsCoreInput: 'Invalid ELS values. Check levels, reference wave, and focus.',
        invalidElsBudgetInput: 'Invalid discount or budget values.',
        notYourSession: 'This enemy stats session belongs to someone else.',
        sessionTimedOut: 'Enemy stats session timed out. Run /enemy_stats again.',
        workshopLeadNote: 'Loaded ELS levels and discounts from your Workshop Tracker.',
      },
      color: 0xf59e0b,
    },
    analytics: {
      name: 'analytics',
      description: 'View command usage analytics for the last 7 days',
      options: {
        days: { name: 'days', description: 'Number of days to look back (default: 7)', min: 1, max: 30 },
      },
      table: {
        commandHeader: 'Command',
      },
      noData: 'No usage data found for the specified period.',
      titlePrefix: 'Command Usage Analytics (Last ',
      titleSuffix: ' Days)',
      color: 0x0099ff,
    },
    checklist: {
      name: 'checklist',
      description: "Make sure you're ready for tournaments",
      defaults: {
        maxSlots: 16,
        baseSlotCount: 12,
        defaultTaskLabelTemplate: 'Task {index}',
        labels: [
          'UWs',
          'Modules',
          'Cards',
          'Labs',
          'Bots',
          'Guardians',
          'Orbs',
          'Range/SW Size',
          'Target Prio',
          'Freeup Locks',
          'Black Background/Theme',
          'Restart Game',
        ],
      },
      behavior: {
        collectorTimeoutMs: 10 * 60 * 1000,
        modalSubmitTimeoutMs: 120000,
        freshnessWindowMs: 24 * 60 * 60 * 1000,
        taskGridRowCount: 4,
        taskGridMaxColumns: 4,
      },
      ids: {
        checkPrefix: 'check_',
        enterEdit: 'enter_edit',
        reset: 'reset_checklist',
        modeSelect: 'mode_select',
        slotSelect: 'slot_select',
        actionConfirm: 'action_confirm',
        actionBack: 'action_back',
        modalSuffix: '_modal_',
        modalInput: 'new_label',
        modeEditValue: 'edit',
        modeAddValue: 'add',
        modeRemoveValue: 'remove',
        noSlotValue: 'none',
      },
      ui: {
        completeEmoji: '✅',
        incompleteEmoji: '⬜',
        slotLabelTemplate: 'Slot {index}',
        assignedLabel: 'Assigned',
        unassignedLabel: 'Use Add Button to Assign',
        title: 'Tourney Checklist',
        description: 'Click the buttons below to mark as complete.',
        progressFieldName: 'Progress',
        color: '#3ac18e',
        editButton: 'Edit Checklist',
        resetButton: 'Reset',
        editTitle: 'Edit Checklist',
        editDescription: 'Manage slots using mode + slot selectors. Back returns to checklist.',
        editColor: '#f1c40f',
        slotsFieldName: 'Slots',
        modePlaceholder: 'Select mode',
        modeEdit: 'Edit Checklist',
        modeAdd: 'Add Button',
        modeRemove: 'Remove Button',
        slotPlaceholder: 'Select a slot',
        noSlotsLabel: 'No slots',
        noSlotsDescription: 'No slots available',
        actionAdd: 'Add',
        actionRemove: 'Remove',
        actionEdit: 'Edit',
        actionBack: 'Back',
        ownershipError: 'This checklist belongs to someone else.',
        sessionTimedOutFooter: 'Checklist session unavailable on this message. Run /checklist again.',
        modalTitleAdd: 'Add to',
        modalTitleEdit: 'Edit',
        modalTitleSlotTemplate: 'Slot {index}',
        modalInputLabel: 'Button label',
        modalInputPlaceholder: 'Enter a label (max 80 chars)',
        closedFooterPrefix: 'Checklist closed',
      },
    },
    remind: {
      name: 'remind',
      description: 'Configure your Tower reminders',
      behavior: {
        collectorTimeoutMs: 10 * 60 * 1000,
      },
      ids: {
        selectPrefix: 'remind_select_',
        pausePrefix: 'remind_pause_',
        toggleTimePrefix: 'remind_toggletime_',
        testPrefix: 'remind_test_',
        stopPrefix: 'stop_reminder_',
      },
      ui: {
        enabledEmoji: '✅',
        disabledEmoji: '❌',
        reminderFieldTemplate: '{emoji} {group}: {title}',
        title: 'Tower Reminders',
        description: 'Use the controls below to enable or disable reminders. Use Test to verify DM delivery.',
        nextReminderPrefix: 'Next Reminder: ',
        exactTimeFormat: ':f',
        relativeTimeFormat: ':R',
        noScheduledTime: 'No scheduled time',
        selectPlaceholder: 'Select reminders to toggle',
        enabledLabel: 'Enabled',
        disabledLabel: 'Disabled',
        pauseLabel: 'Pause All Reminders',
        resumeLabel: 'Resume All Reminders',
        showExactLabel: 'Show Exact Times',
        showRelativeLabel: 'Show Relative Times',
        sendTestLabel: 'Send Test Reminder',
        unknownComponent: 'Unknown component.',
        testSent: 'Test reminder sent to your DMs.',
        testFailedPrefix: 'Unable to send test reminder: ',
        dmAlertTitle: 'Reminder Alert!',
          collectorUnavailable: 'Reminder controls are unavailable on this message. Run /remind again.',
        dmNextReminderField: 'Next Reminder',
        dmReminderLineTemplate: '{group} - {title}',
        dmNoScheduledTime: 'No scheduled time',
        dmFooter: 'Use /remind in tower server to edit your reminders',
        dmStopButtonLabel: 'Stop This Reminder',
        dmStopUnauthorized: 'You are not authorized to stop this reminder.',
        dmStopConfirmed: 'This reminder has been stopped for you.',
        dmUserNotFound: 'User not found',
        dmTestFieldName: 'Test Reminder',
        dmTestFieldValue: 'This is a test reminder to confirm you can receive DMs from the bot.',
        dmTestNextValue: 'Test',
        dmBlockedReason: 'I cannot send you Direct Messages. Please enable DMs from server members and ensure you have not blocked the bot.',
        dmSendFailedPrefix: 'Failed to send DM: ',
      },
    },
    earnings: {
      name: 'earnings',
      description: 'Analyze earnings CSV export and return a summary',
      options: {
        csvFile: { name: 'csv_file', description: 'CSV export file to analyze' },
      },
      invalidFile: 'Please upload a valid `.csv` file.',
      emptyRows: 'CSV parsed successfully, but no rows were found.',
      noData: 'No data',
      title: 'Earnings Summary',
      summaryDescription: 'CSV analysis complete.',
      totalsField: 'Totals',
      dateRangeField: 'Date Range',
      topProductsField: 'Top Products',
      topPlatformsField: 'Top Platforms',
      topStatusesField: 'Top Statuses',
      unknownDateRange: 'Unknown',
      totalsRevenueLabel: 'Revenue',
      totalsSalesLabel: 'Sales',
      totalsAvgRevenueLabel: 'Avg Revenue/Sale',
      processErrorPrefix: 'Unable to process CSV: ',
      processUnknownError: 'Unknown error',
      color: 0x2b6ef2,
    },
    settings: {
      name: 'settings',
      description: 'View or update shared tool settings',
      options: {
        cloudSync: {
          name: 'cloud_sync',
          description: 'Enable or disable cloud sync preference',
        },
        chartPalette: {
          name: 'chart_palette',
          description: 'Select your chart palette preset',
        },
        chartAlignment: {
          name: 'chart_alignment',
          description: 'Select your chart data alignment preference',
        },
        language: {
          name: 'language',
          description: 'Select your interface language preference',
        },
        dateFormat: {
          name: 'date_format',
          description: 'Select your preferred date format',
        },
        decimalSeparator: {
          name: 'decimal_separator',
          description: 'Select your preferred decimal indicator',
        },
        cloudChoices: {
          enabled: 'Enabled',
          disabled: 'Disabled',
        },
        alignmentChoices: {
          left: 'Left',
          center: 'Center',
          right: 'Right',
        },
      },
      ids: {
        cloudSyncSelect: 'settings_cloud_sync_select',
        chartPaletteSelect: 'settings_chart_palette_select',
        chartAlignmentSelect: 'settings_chart_alignment_select',
        languageSelect: 'settings_language_select',
        dateFormatSelect: 'settings_date_format_select',
        decimalSeparatorSelect: 'settings_decimal_separator_select',
      },
      ui: {
        title: 'Tools Settings',
        currentMessage: 'Current saved settings:',
        savedMessage: 'Settings updated successfully.',
        linkRequiredMessage: 'Linked account required before tool settings can be synced. Ask a mod/admin to link your Discord account to your Appwrite user ID.',
        cloudField: 'Cloud Sync Preference',
        paletteField: 'Chart Palette Preset',
        alignmentField: 'Chart Data Alignment',
        languageField: 'Language',
        dateFormatField: 'Date Format',
        decimalSeparatorField: 'Decimal Indicator',
        scopeField: 'Sync Scope',
        scopeNote: 'This first slice saves locally for the bot. Cloud sync preference is stored for activation once account-link sync is enabled.',
        enabled: 'Enabled',
        disabled: 'Disabled',
        nonDefaultFooter: 'Using non-default settings.',
        cloudPlaceholder: 'Cloud Sync Preference',
        palettePlaceholder: 'Chart Palette Preset',
        alignmentPlaceholder: 'Chart Data Alignment',
        languagePlaceholder: 'Language Preference',
        dateFormatPlaceholder: 'Date Format Preference',
        decimalSeparatorPlaceholder: 'Decimal Indicator Preference',
        autoOptionLabel: 'Auto (Region Default)',
      },
      color: 0x8b5cf6,
    },
    shardSplitter: {
      name: 'shard',
      description: 'Optimize module shard split between primary and assist stats',
      behavior: {
        collectorTimeoutMs: 10 * 60 * 1000,
        modalSubmitTimeoutMs: 120000,
      },
      options: {
        type: {
          name: 'type',
          description: 'Module type (cannon, defense, generator, core)',
        },
        assistEff: {
          name: 'assist_eff',
          description: 'Assist efficiency %',
        },
        unspentShards: {
          name: 'unspent_shards',
          description: 'Unspent shards',
        },
        primaryLevel: {
          name: 'primary_level',
          description: 'Primary level',
        },
        assistLevel: {
          name: 'assist_level',
          description: 'Assist level',
        },
      },
      moduleChoices: [
        { name: 'Cannon', value: 'cannon' },
        { name: 'Defense', value: 'defense' },
        { name: 'Generator', value: 'generator' },
        { name: 'Core', value: 'core' },
      ],
      ids: {
        moduleSelect: 'splitter_module_select',
        settingsButton: 'splitter_settings_button',
        levelsButton: 'splitter_levels_button',
        setButton: 'splitter_set_button',
        settingsModal: 'splitter_settings_modal',
        levelsModal: 'splitter_levels_modal',
        inputUnspentShards: 'splitter_input_unspent_shards',
        inputAssistEff: 'splitter_input_assist_eff',
        inputShardDiscount: 'splitter_input_shard_discount',
        inputPrimaryLevel: 'splitter_input_primary_level',
        inputSecondaryLevel: 'splitter_input_secondary_level',
        inputPrimaryRarity: 'splitter_input_primary_rarity',
        inputSecondaryRarity: 'splitter_input_secondary_rarity',
      },
      ui: {
        title: 'Shard Splitter',
        description: 'Use the buttons below to set your module levels and see your most optimal shard split.',
        unlinkedDescription: 'Using local-only storage. Enable cloud saves for full website settings parity.',
        websiteUrl: 'https://the-tower-run-tracker.com/calculators/shard-splitter',
        linkedFooter: 'Shard Splitter: https://the-tower-run-tracker.com/calculators/shard-splitter',
        unlinkedFooter: 'Shard Splitter: https://the-tower-run-tracker.com/calculators/shard-splitter',
        modulePlaceholder: 'Select module type',
        settingsButtonLabel: 'Settings',
        levelsButtonLabel: 'Levels',
        setButtonLabel: 'Set',
        settingsModalTitle: 'Shard Splitter Settings',
        levelsModalTitle: 'Shard Splitter Levels',
        primaryRarityPlaceholder: 'Select primary rarity',
        assistRarityPlaceholder: 'Select assist rarity',
        inputUnspentShardsLabel: 'Unspent Shards (0+)',
        inputAssistEffLabel: 'Assist Efficiency % (0-100)',
        inputShardDiscountLabel: 'Shard Discount % (0-30)',
        inputPrimaryLevelLabel: 'Primary Level (1-300)',
        inputSecondaryLevelLabel: 'Assist Level (1-300)',
        inputPrimaryRarityLabel: 'Primary Rarity (e.g. Mythic +)',
        inputSecondaryRarityLabel: 'Assist Rarity (e.g. Ancestral)',
        invalidSettingsInput: 'Invalid settings values. Check discount (0-30) and rarity values and try again.',
        invalidLevelsInput: 'Invalid levels values. Check assist eff/shards/level ranges and try again.',
        invalidRarityTemplate: 'Invalid rarity. Valid rarities: {rarities}',
        invalidLevelsTemplate: 'Invalid levels. Primary must be 1-{primaryCap}; Assist must be 1-{secondaryCap}.',
        currentModuleField: 'Module',
        currentLevelsField: 'Levels (P/A)',
        currentRarityField: 'Rarity (P/A)',
        unspentField: 'Unspent Shards',
        assistField: 'Assist Efficiency',
        discountField: 'Shard Discount',
        budgetField: 'Budget',
        budgetValueTemplate: 'Base Cost: {base}\nTotal Budget: {total}',
        bestField: 'Best Result',
        bestValueTemplate: 'Target P/A: {p}/{s}\nRemaining: {remain}',
        nextField: 'Next Best Result',
        nextValueTemplate: '{tag}\nTarget P/A: {p}/{s}\nRemaining: {remain}',
        nextBestCurrentBudgetTag: 'Current budget',
        nextBestExtraTemplate: 'Requires +{extra} shards',
        noResult: 'No result available for current inputs.',
        setApplied: 'Applied suggested split for {module}: P/A {p}/{a}. New default levels are saved.',
        setAppliedWebPending: 'Web tracker sync is not yet configured in this bot runtime. Local shard defaults were updated.',
        chartTitleTemplate: 'Shard Splitter — {module}',
        chartMetricHeader: 'Metric',
        chartBestHeader: 'Best',
        chartNextHeader: 'Next Best',
        metricPrimaryTarget: 'Primary Target',
        metricAssistTarget: 'Assist Target',
        metricPrimarySpent: 'Primary Shards Spent',
        metricAssistSpent: 'Assist Shards Spent',
        metricRemaining: 'Shards Remaining',
        metricEffective: 'Total Effective Bonus',
        chartFileName: 'shard-splitter.png',
        notYourSession: 'This shard splitter session belongs to someone else.',
      },
      color: 0x06b6d4,
    },
    guardian: {
      name: 'guardian',
      description: 'Show guardian stats and upgrade costs by level',
      behavior: {
        collectorTimeoutMs: 10 * 60 * 1000,
        modalSubmitTimeoutMs: 120000,
      },
      options: {
        type: {
          name: 'type',
          description: 'Guardian type (attack, ally, bounty, fetch, summon, scout)',
        },
        startLevel: {
          name: 'start_level',
          description: 'Start level',
        },
        targetLevel: {
          name: 'target_level',
          description: 'Target level',
        },
        stat: {
          name: 'stat',
          description: 'Filter by stat name (or "all")',
        },
      },
      ids: {
        typeSelect: 'guardian_type_select',
        statSelect: 'guardian_stat_select',
        setLevel: 'guardian_set_level',
        levelModal: 'guardian_level_modal',
        startLevelInput: 'guardian_start_level_input',
        targetLevelInput: 'guardian_target_level_input',
      },
      ui: {
        titleTemplate: 'Guardian: {guardian} — Levels {start} → {target}/{max}',
        description: 'Use the settings below to calculate costs for Guardians',
        statLineTemplate: 'Value: **{value}**\nCost: **{cost}**',
        unknownTypeTemplate: 'Unknown guardian type: `{type}`',
        fallbackTitle: 'Guardian Calculator',
        fallbackDescription: 'No guardian data available.',
        typePlaceholder: 'Select guardian type',
        statPlaceholder: 'Filter by stat',
        statAllLabel: 'All Stats',
        statAllDescription: 'Show all guardian stats',
        statDescriptionTemplate: 'Show {stat} only',
        setLevelLabel: 'Set Level',
        levelModalTitle: 'Guardian Level Range',
        startLevelInputLabel: 'Start Level',
        targetLevelInputLabel: 'Target Level',
        invalidLevelTemplate: 'Invalid levels. Enter values between {min} and {max}, with target >= start.',
        modalTimedOut: 'Guardian level modal timed out. Click Set Level to try again.',
        notYourSession: 'This guardian calculator session belongs to someone else.',
        noneValue: '—',
      },
      color: 0x22c55e,
    },
    reload: {
      name: 'reload',
      description: 'Validate a command name and explain reload behavior in TS runtime.',
      options: {
        command: { name: 'command', description: 'The command to validate' },
      },
      notFoundTemplate: 'There is no command with name `{commandName}`.',
      registeredTemplate: 'Command `{commandName}` is registered. TS runtime hot-reload is not supported; restart the bot process to load code changes.',
    },
    eightBall: {
      name: '8ball',
      description: 'Ask the Magic 8-Ball a question',
      behavior: {
        deferReply: true,
        ephemeral: false,
      },
      ai: {
        endpoint: 'https://api.groq.com/openai/v1/chat/completions',
        model: 'qwen/qwen3-32b',
        maxTokens: 100,
        temperature: 0.9,
        timeoutMs: 15000,
        systemPrompt: [
          'You are a smart, self-aware 8-ball.',
          'Answer with brief, clever responses that go beyond yes/no/maybe while staying concise.',
          'Tone: slightly mean, sarcastic, witty, and unimpressed.',
          'Do not sound warm, supportive, or encouraging.',
          'A little mockery is fine, but keep it playful rather than abusive.',
          'Do not add long explanations.',
        ].join(' '),
      },
      aiErrorResponse: 'Oops! My circuits got tangled. Try again.',
      options: {
        message: { name: 'message', description: 'What do you want to ask?' },
        deepReasoning: { name: 'deep-reasoning', description: 'Use the deeper reasoning model for a slower, more detailed answer.' },
      },
      responseTemplate: '> {question}\n{answer}',
      responses: [
        'Sure. Try not to ruin it.',
        'Most likely. Which is surprising, honestly.',
        'Ask again later. I\'m on my break.',
        'Hard to say. Your judgment is not helping.',
        'Reply hazy. So, business as usual for you.',
        'Outlook decent. Your execution is the weaker variable.',
        'Very doubtful. Bold of you to ask anyway.',
        'No. I thought that was obvious.',
        'You can rely on it about as much as your planning skills.',
        'I\'d avoid that if you enjoy avoiding embarrassment.',
      ],
    },
    ask: {
      name: 'ask',
      description: 'Ask TowerAI a Question.',
      behavior: {
        deferReply: true,
        ephemeral: true,
      },
      options: {
        message: { name: 'message', description: 'Ask a question about The Tower' },
        deepReasoning: { name: 'deep-reasoning', description: 'Use the deeper reasoning model for a slower, more detailed answer.' },
      },
      aiErrorResponse: 'TowerAI could not answer right now. Try again in a moment.',
    },
  },
} as const;

export type ToolsBotConfig = typeof defaultBotConfig;

let runtimeConfig: ToolsBotConfig = defaultBotConfig;

export function getBotConfig(): ToolsBotConfig {
  return runtimeConfig;
}

export function resetBotConfig(): ToolsBotConfig {
  runtimeConfig = defaultBotConfig;
  return runtimeConfig;
}
